language: python

python:
  - "2.7"
  - "3.4"

# Use the new travis docker based infrastructure
sudo: false

cache: apt
cache: pip

# Install required packages
addons:
  postgresql: "9.4"
  apt:
    packages:
    - libhdf5-serial-dev
    - libnetcdf-dev
    - libproj-dev
    - libgdal1-dev

before_install:
  # Create a database for the integration tests.
  - createdb agdcintegration

install:
  - pip install -r requirements.txt coveralls
  - python setup.py install

script:
  - ./check-code.sh integration_tests

after_success:
  - coveralls
