language: python

python:
  - "2.7"
  - "3.4"

# Use the new travis docker based infrastructure
sudo: false

cache: apt
cache: pip

# Install required packages
addons:
  postgresql: "9.4"
  apt:
    packages:
    - libhdf5-serial-dev
    - libnetcdf-dev
    - libproj-dev
    - libgdal1-dev
    - libudunits2-0 # Used by cf-checker

before_install:
  # Create a database for the integration tests.
  - createdb agdcintegration

install:
  - export CPLUS_INCLUDE_PATH="/usr/include/gdal"
  - export C_INCLUDE_PATH="/usr/include/gdal"
  - pip install -r requirements.txt coveralls gdal==1.10.0
  - easy_install cdat-lite cfchecker
  - python setup.py install

script:
  - ./check-code.sh integration_tests

after_success:
  - coveralls
